name: {{ cookiecutter.repo_name }}
channels:
  - conda-forge
  - defaults
  - r
dependencies:
  - r-base
  - r-dotenv
  - r-dplyr
  - r-ggplot2
  - r-glue
  - r-here
  - r-optparse
  - r-readr
  - r-scales
  - r-styler
